{ ... }:

{
  fonts.fontconfig.ultimate = {
    enable = true;
  };

  environment.variables = {
    # Windows 10-like font rendering config for Linux
    # See https://gist.github.com/sorenvonsarvort/fa6c5341403bf306e23034a1a1a9111b
    INFINALITY_FT_FILTER_PARAMS = "8 17 50 17 8";
    INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH = "0";
    INFINALITY_FT_FRINGE_FILTER_STRENGTH = "55";
    INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH = "0";
    INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH = "0";
    INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH = "20";
    INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH = "0";
    INFINALITY_FT_STEM_ALIGNMENT_STRENGTH = "0";
    INFINALITY_FT_STEM_FITTING_STRENGTH = "100";
    INFINALITY_FT_STEM_DARKENING_AUTOFIT = "false";
    INFINALITY_FT_STEM_DARKENING_CFF = "false";
    INFINALITY_FT_GAMMA_CORRECTION = " 0  100";
    INFINALITY_FT_BRIGHTNESS = "60";
    INFINALITY_FT_CONTRAST = "0";
    INFINALITY_FT_USE_VARIOUS_TWEAKS = "false";
    INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS = "false";
    INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT = "100";
    INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE = "0";
    INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS = "false";

    INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE = "35";
    INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE = "0";
    INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE = "0";
    INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE = "0";
  };
}
