# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/962cbd87-fd5b-4a4a-8635-b13005abad14";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/a719a92e-dc50-47cb-a834-ddd492c56d5f";
  boot.initrd.luks.devices."cryptswap".device = "/dev/disk/by-uuid/c32f0aa5-2f27-4a20-9d26-4e6c5daac8c8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3224-D290";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/21d4e415-f1b0-4cd8-9511-278a2fe21cc7"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
