{
 "title": "ETFs",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "MAG",
    "query": "AAPL, MSFT, GOOGL, AMZN, META, NVDA, TSLA, NFLX, UBER"
   },
   { "name": "Collapse", "query": "day, week, month" },
   {
    "name": "NASDAQ_100",
    "label": "NASDAQ-100",
    "query": "AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,AMZN,ANSS,ASML,AVGO,AZN,BIIB,BKNG,BKR,CCEP,CDNS,CDW,CEG,CHTR,CMCSA,COST,CPRT,CRWD,CSCO,CSGP,CSX,CTAS,CTSH,DASH,DDOG,DLTR,DXCM,EA,EXC,FANG,FAST,FTNT,GEHC,GFS,GILD,GOOG,GOOGL,HON,IDXX,ILMN,INTC,INTU,ISRG,KDP,KHC,KLAC,LRCX,LULU,MAR,MCHP,MDB,MDLZ,MELI,META,MNST,MRNA,MRVL,MSFT,MU,NFLX,NVDA,NXPI,ODFL,ON,ORLY,PANW,PAYX,PCAR,PDD,PEP,PYPL,QCOM,REGN,ROP,ROST,SBUX,SIRI,SNPS,SPLK,TEAM,TMUS,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBA,WBD,WDAY,XEL,ZS"
   },
   {
    "name": "SP500",
    "label": "S&P500",
    "query": "MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,APD,ABNB,AKAM,ALB,ARE,ALGN,ALLE,LNT,ALL,GOOGL,GOOG,MO,AMZN,AMCR,AEE,AAL,AEP,AXP,AIG,AMT,AWK,AMP,AME,AMGN,APH,ADI,ANSS,AON,APA,AAPL,AMAT,APTV,ACGL,ADM,ANET,AJG,AIZ,T,ATO,ADSK,ADP,AZO,AVB,AVY,AXON,BKR,BALL,BAC,BK,BBWI,BAX,BDX,BRK.B,BBY,BIO,TECH,BIIB,BLK,BX,BA,BKNG,BWA,BXP,BSX,BMY,AVGO,BR,BRO,BF.B,BLDR,BG,CDNS,CZR,CPT,CPB,COF,CAH,KMX,CCL,CARR,CTLT,CAT,CBOE,CBRE,CDW,CE,COR,CNC,CNP,CF,CHRW,CRL,SCHW,CHTR,CVX,CMG,CB,CHD,CI,CINF,CTAS,CSCO,C,CFG,CLX,CME,CMS,KO,CTSH,CL,CMCSA,CMA,CAG,COP,ED,STZ,CEG,COO,CPRT,GLW,CTVA,CSGP,COST,CTRA,CCI,CSX,CMI,CVS,DHR,DRI,DVA,DAY,DE,DAL,XRAY,DVN,DXCM,FANG,DLR,DFS,DG,DLTR,D,DPZ,DOV,DOW,DHI,DTE,DUK,DD,EMN,ETN,EBAY,ECL,EIX,EW,EA,ELV,LLY,EMR,ENPH,ETR,EOG,EPAM,EQT,EFX,EQIX,EQR,ESS,EL,ETSY,EG,EVRG,ES,EXC,EXPE,EXPD,EXR,XOM,FFIV,FDS,FICO,FAST,FRT,FDX,FIS,FITB,FSLR,FE,FI,FLT,FMC,F,FTNT,FTV,FOXA,FOX,BEN,FCX,GRMN,IT,GEHC,GEN,GNRC,GD,GE,GIS,GM,GPC,GILD,GPN,GL,GS,HAL,HIG,HAS,HCA,PEAK,HSIC,HSY,HES,HPE,HLT,HOLX,HD,HON,HRL,HST,HWM,HPQ,HUBB,HUM,HBAN,HII,IBM,IEX,IDXX,ITW,ILMN,INCY,IR,PODD,INTC,ICE,IFF,IP,IPG,INTU,ISRG,IVZ,INVH,IQV,IRM,JBHT,JBL,JKHY,J,JNJ,JCI,JPM,JNPR,K,KVUE,KDP,KEY,KEYS,KMB,KIM,KMI,KLAC,KHC,KR,LHX,LH,LRCX,LW,LVS,LDOS,LEN,LIN,LYV,LKQ,LMT,L,LOW,LULU,LYB,MTB,MRO,MPC,MKTX,MAR,MMC,MLM,MAS,MA,MTCH,MKC,MCD,MCK,MDT,MRK,META,MET,MTD,MGM,MCHP,MU,MSFT,MAA,MRNA,MHK,MOH,TAP,MDLZ,MPWR,MNST,MCO,MS,MOS,MSI,MSCI,NDAQ,NTAP,NFLX,NEM,NWSA,NWS,NEE,NKE,NI,NDSN,NSC,NTRS,NOC,NCLH,NRG,NUE,NVDA,NVR,NXPI,ORLY,OXY,ODFL,OMC,ON,OKE,ORCL,OTIS,PCAR,PKG,PANW,PARA,PH,PAYX,PAYC,PYPL,PNR,PEP,PFE,PCG,PM,PSX,PNW,PXD,PNC,POOL,PPG,PPL,PFG,PG,PGR,PLD,PRU,PEG,PTC,PSA,PHM,QRVO,PWR,QCOM,DGX,RL,RJF,RTX,O,REG,REGN,RF,RSG,RMD,RVTY,RHI,ROK,ROL,ROP,ROST,RCL,SPGI,CRM,SBAC,SLB,STX,SRE,NOW,SHW,SPG,SWKS,SJM,SNA,SO,LUV,SWK,SBUX,STT,STLD,STE,SYK,SYF,SNPS,SYY,TMUS,TROW,TTWO,TPR,TRGP,TGT,TEL,TDY,TFX,TER,TSLA,TXN,TXT,TMO,TJX,TSCO,TT,TDG,TRV,TRMB,TFC,TYL,TSN,USB,UBER,UDR,ULTA,UNP,UAL,UPS,URI,UNH,UHS,VLO,VTR,VLTO,VRSN,VRSK,VZ,VRTX,VFC,VTRS,VICI,V,VMC,WRB,WAB,WBA,WMT,DIS,WBD,WM,WAT,WEC,WFC,WELL,WST,WDC,WRK,WY,WHR,WMB,WTW,GWW,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZION,ZTS"
   },
   {
    "name": "RUSSEL_1000",
    "label": "RUSSEL 1000 GROWTH",
    "query": "TXG,MMM,ABT,ABBV,ACHC,ACN,AYI,ADM,ADBE,ADP,ADT,AAP,WMS,ACM,AES,AFRM,AFL,AGCO,A,AGL,ADC,AGNC,AIG,AL,APD,ABNB,AKAM,ALK,ALB,ACI,AA,ARE,ALGN,ALLE,ALGM,LNT,ALSN,ALL,ALLY,ALNY,GOOGL,GOOG,AYX,MO,AMZN,AMC,AMCR,AMD,DOX,AMED,AEE,AAL,AEP,AXP,AFG,AMH,AMT,AWK,COLD,AMP,AME,AMG,AMGN,APH,ADI,NLY,ANSS,AM,AR,AON,APA,AIRC,APLS,APO,AAPL,AMAT,APP,ATR,APTV,ARMK,ACGL,AMBP,ARES,ANET,AWI,ARW,AJG,ASH,AZPN,AIZ,AGO,T,TEAM,ATO,ADSK,AN,AZO,AVB,AGR,AVTR,AVY,CAR,AVT,AXTA,AXS,AXON,AZEK,AZTA,BKR,BALL,BAC,OZK,BBWI,BAX,BDX,BSY,WRB,BRK.B,BERY,BBY,BILL,BIO,TECH,BIIB,BMRN,BIRK,BJ,BLK,BX,HRB,SQ,OWL,BK,BA,BOKF,BKNG,BAH,BWA,SAM,BXP,BSX,BYD,BFAM,BHF,BMY,BRX,AVGO,BR,BEPC,BRO,BF.A,BF.B,BRKR,BC,BLDR,BG,BURL,BWXT,CHRW,CABO,CACI,CDNS,CZR,CPT,CPB,COF,CPRI,CAH,CSL,CG,KMX,CCL,CARR,CRI,CASY,CTLT,CAT,CAVA,CBOE,CBRE,CCCS,CDW,CE,CELH,COR,CNC,CNP,CERT,CF,CHPT,CRL,SCHW,CHTR,CHE,CC,LNG,CHK,CVX,CMG,CHH,CB,CHD,CHDN,CIEN,CI,CINF,CTAS,CRUS,CSCO,C,CFG,CLVT,CLH,CWEN.A,CWEN,CLF,CLX,NET,CME,CMS,CNA,CNHI,KO,CGNX,CTSH,COHR,COIN,CL,COLB,COLM,CMCSA,CMA,CBSH,ED,CAG,CNXC,CFLT,COP,STZ,CEG,COO,CPRT,CNM,GLW,CTVA,CSGP,COST,CTRA,COTY,CPNG,CUZ,CR,CXT,CACC,CROX,CRWD,CCI,CCK,CSX,CUBE,CMI,CW,CVS,DHI,DHR,DRI,DAR,DDOG,DVA,DAY,DECK,DE,DAL,XRAY,DVN,DXCM,FANG,DKS,DLR,DFS,DIS,DOCU,DLB,DG,DLTR,D,DPZ,DCI,DASH,DV,DOV,DOW,DOCS,DKNG,DRVN,DBX,DTM,DTE,DUK,DNB,DD,DXC,DT,EXP,EWBC,EGP,EMN,ETN,EBAY,ECL,EIX,EW,ELAN,ESTC,EA,ESI,ELV,EME,EMR,EHC,ENOV,ENPH,ENTG,ETR,NVST,EOG,EPAM,EPR,EQT,EFX,EQIX,EQH,ELS,EQR,ESAB,WTRG,ESS,EL,ETSY,EEFT,EVR,EG,EVRG,ES,EXAS,EXEL,EXC,EXPE,EXPD,EXR,XOM,FFIV,FDS,FAST,FRT,FDX,FERG,FICO,FNF,FITB,FAF,FCNCA,FHB,FHN,FR,FSLR,FE,FIS,FI,FIVE,FIVN,FLT,FND,FLO,FLS,FMC,FNB,F,FTNT,FTV,FTRE,FBIN,FOXA,FOX,BEN,FCX,FRPT,FYBR,CFR,FCN,GME,GLPI,GPS,GRMN,IT,GTES,GE,GEHC,GEN,GNRC,GD,GIS,GM,G,GNTX,GPC,GILD,DNA,GTLB,GPN,GFS,GLOB,GL,GMED,GDDY,GS,GGG,GWW,LOPE,GPK,GO,GWRE,GXO,HAL,THG,HOG,HIG,HAS,HCP,HE,HAYW,HCA,HR,PEAK,HEI.A,HEI,JKHY,HSY,HTZ,HES,HPE,HXL,DINO,HIW,HLT,HOLX,HD,HON,HRL,HST,HLI,HHH,HWM,HPQ,HUBB,HUBS,HUM,HBAN,HII,HUN,H,IAC,IBM,ICLR,ICUI,IDA,IEX,IDXX,ITW,ILMN,INCY,INFA,IR,INGR,INSP,PODD,IART,INTC,IBKR,ICE,IFF,IP,INTU,ISRG,IVZ,INVH,IONS,IPG,IPGP,IQV,IRDM,IRM,ITT,JBL,J,JHG,JAZZ,JBHT,JEF,JNJ,JCI,JLL,JPM,JNPR,KRTX,KBR,K,KMPR,KVUE,KDP,KEY,KEYS,KRC,KMB,KIM,KMI,KNSL,KEX,KKR,KLAC,KNX,KSS,KHC,KR,KD,LHX,LH,LRCX,LAMR,LW,LSTR,LVS,LSCC,LAZ,LEA,LEG,LDOS,LEN,LEN.B,LII,LBRDA,LBRDK,FWONA,FWONK,LLYVA,LLYVK,LSXMA,LSXMK,LLY,LECO,LNC,LIN,LAD,LFUS,LYV,LKQ,LMT,L,LPX,LOW,LPLA,LCID,LULU,LITE,LYFT,LYB,MTB,M,MSGS,MANH,MAN,CART,MRO,MPC,MRVI,MKL,MKTX,MAR,VAC,MMC,MLM,MRVL,MAS,MASI,MTZ,MA,MTCH,MAT,MKC,MCD,MCK,MDU,MPW,MEDP,MDT,MRK,MRCY,META,MET,MTD,MTG,MGM,MCHP,MU,MSFT,MAA,MIDD,MRTX,MCW,MKSI,MRNA,MHK,MOH,TAP,MDLZ,MDB,MPWR,MNST,MCO,MS,MORN,MOS,MSI,MP,MSA,MSM,MSCI,MUSA,NDAQ,NTRA,NFG,NSA,NCNO,NATL,VYX,NLOP,NTAP,NFLX,NBIX,NFE,NYCB,NYT,NWL,NEU,NEM,NWSA,NWS,NXST,NEE,NKE,NI,NNN,NDSN,JWN,NSC,NTRS,NOC,NCLH,NOV,NVCR,NRG,NU,NUE,NTNX,NVT,NVDA,NVR,ORLY,OXY,OGE,OKTA,OLPX,ODFL,ORI,OLN,OLLI,OHI,OMC,ON,OMF,OKE,ORCL,OGN,OSK,OTIS,OVV,OC,PCAR,PKG,PLTR,PANW,PARAA,PARA,PK,PH,PAYX,PAYC,PYCR,PCTY,PYPL,PEGA,PTON,PENN,PAG,PNR,PEN,PEP,PFGC,PRGO,WOOF,PFE,PCG,PM,PSX,PHIN,PPC,PNFP,PNW,PINS,PXD,PLNT,PLTK,PLUG,PNC,PII,POOL,BPOP,POST,PPG,PPL,PINC,TROW,PRI,PFG,PCOR,PG,PGR,PLD,PB,PRU,PTC,PSA,PEG,PHM,PSTG,PVH,QGEN,QRVO,QCOM,PWR,QS,DGX,QDEL,RCM,RL,RRC,RJF,RYN,RTX,RBC,O,RRX,REG,REGN,RF,RGA,RS,RNR,RGEN,RSG,RMD,RVTY,REXR,REYN,RH,RNG,RBA,RITM,RIVN,RLI,RHI,HOOD,RBLX,RKT,ROK,ROIV,ROKU,ROL,ROP,ROST,RCL,RGLD,RPRX,RPM,RYAN,R,SPGI,SAIA,SAIC,CRM,SLM,SRPT,SBAC,HSIC,SLB,SNDR,SMG,SEB,SEE,SEIC,SRE,ST,S,SCI,NOW,SHW,FOUR,SWAV,SLGN,SPG,SIRI,SITE,SKX,SWKS,SMAR,AOS,SJM,SNA,SNOW,SOFI,SON,SHC,SO,SCCO,LUV,SWN,SPB,SPR,SPLK,SPOT,SSNC,SSRM,STAG,SWK,SBUX,STWD,STT,STLD,SRCL,STE,SF,SYK,SUI,RUN,SYF,SNPS,SNV,SYY,TMUS,TTWO,TNDM,TPR,TRGP,TGT,SNX,FTI,TDOC,TDY,TFX,TPX,THC,TDC,TER,TSLA,TTEK,TXN,TPL,TXRH,TXT,TMO,TFSL,THO,TKR,TJX,TKO,TOST,TOL,BLD,TTC,TPG,TSCO,TTD,TW,TT,TDG,TRU,TNL,TRV,TREX,TRMB,TRIP,TFC,TWLO,TYL,TSN,UHAL,UHAL.B,X,UBER,UI,UDR,UGI,PATH,ULTA,RARE,UAA,UA,UNP,UAL,UPS,URI,UTHR,UWMC,UNH,U,OLED,UHS,UNM,USB,USFD,MTN,VLO,VMI,VVV,VEEV,VTR,VLTO,VRSN,VRSK,VZ,VRTX,VRT,VSTS,VFC,VSAT,VTRS,VICI,VSCO,VIRT,V,VST,VNT,VNO,VOYA,VMC,WPC,WAB,WBA,WMT,WBD,WM,WAT,WSO,W,WBS,WEC,WFC,WELL,WEN,WCC,WST,WAL,WDC,WU,WLK,WRK,WEX,WY,WHR,WTM,WMB,WSM,WTW,WSC,WING,WTFC,KLG,WOLF,WWD,WDAY,WH,WYNN,XEL,XP,XPO,XYL,YETI,YUM,ZBRA,ZG,Z,ZBH,ZION,ZTS,ZM,ZI,ZS"
   }
  ]
 },
 "panels": [
  { "title": "MAGS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MAGS",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(symbol) (security_Open{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "max by(symbol) (security_Close{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Close"
    },
    {
     "expr": "max by(symbol) (security_High{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "High"
    },
    {
     "expr": "max by(symbol) (security_Low{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "max by(symbol) (security_Volume{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "MAGS Individual Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$MAG",
     "type": "candlestick",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "repeat": "MAG",
     "targets": [
      {
       "expr": "max by(symbol) (security_Open{symbol=~\"$MAG\", collapse=\"day\"})",
       "legendFormat": "Open"
      },
      {
       "expr": "max by(symbol) (security_Close{symbol=~\"$MAG\", collapse=\"$Collapse\"})",
       "legendFormat": "Close"
      },
      {
       "expr": "max by(symbol) (security_Low{symbol=~\"$MAG\", collapse=\"day\"})",
       "legendFormat": "Low"
      },
      {
       "expr": "max by(symbol) (security_High{symbol=~\"$MAG\", collapse=\"day\"})",
       "legendFormat": "High"
      },
      {
       "expr": "max by(symbol) (security_Volume{symbol=~\"$MAG\", collapse=\"day\"})",
       "legendFormat": "Volume"
      }
     ]
    }
   ]
  },
  { "title": "VONG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "MAGS",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by(symbol) (security_Open{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "max by(symbol) (security_Close{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Close"
    },
    {
     "expr": "max by(symbol) (security_High{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "High"
    },
    {
     "expr": "max by(symbol) (security_Low{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "max by(symbol) (security_Volume{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "VONG Individual Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$RUSSEL_1000",
     "type": "candlestick",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "repeat": "RUSSEL_1000",
     "targets": [
      {
       "expr": "max by(symbol) (security_Open{symbol=~\"$RUSSEL_1000\", collapse=\"day\"})",
       "legendFormat": "Open"
      },
      {
       "expr": "max by(symbol) (security_Close{symbol=~\"$RUSSEL_1000\", collapse=\"$Collapse\"})",
       "legendFormat": "Close"
      },
      {
       "expr": "max by(symbol) (security_Low{symbol=~\"$RUSSEL_1000\", collapse=\"day\"})",
       "legendFormat": "Low"
      },
      {
       "expr": "max by(symbol) (security_High{symbol=~\"$RUSSEL_1000\", collapse=\"day\"})",
       "legendFormat": "High"
      },
      {
       "expr": "max by(symbol) (security_Volume{symbol=~\"$RUSSEL_1000\", collapse=\"day\"})",
       "legendFormat": "Volume"
      }
     ]
    }
   ]
  },
  { "title": "QQQM / QQQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "MAGS",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max by(symbol) (security_Open{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "max by(symbol) (security_Close{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Close"
    },
    {
     "expr": "max by(symbol) (security_High{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "High"
    },
    {
     "expr": "max by(symbol) (security_Low{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "max by(symbol) (security_Volume{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "MAGS",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "max by(symbol) (security_Open{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "max by(symbol) (security_Close{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Close"
    },
    {
     "expr": "max by(symbol) (security_High{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "High"
    },
    {
     "expr": "max by(symbol) (security_Low{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "max by(symbol) (security_Volume{symbol=~\"MAGS\", collapse=\"$Collapse\"})",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "QQQM Individual Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$NASDAQ_100",
     "type": "candlestick",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "repeat": "NASDAQ_100",
     "targets": [
      {
       "expr": "max by(symbol) (security_Open{symbol=~\"$NASDAQ_100\", collapse=\"day\"})",
       "legendFormat": "Open"
      },
      {
       "expr": "max by(symbol) (security_Close{symbol=~\"$NASDAQ_100\", collapse=\"$Collapse\"})",
       "legendFormat": "Close"
      },
      {
       "expr": "max by(symbol) (security_Low{symbol=~\"$NASDAQ_100\", collapse=\"day\"})",
       "legendFormat": "Low"
      },
      {
       "expr": "max by(symbol) (security_High{symbol=~\"$NASDAQ_100\", collapse=\"day\"})",
       "legendFormat": "High"
      },
      {
       "expr": "max by(symbol) (security_Volume{symbol=~\"$NASDAQ_100\", collapse=\"day\"})",
       "legendFormat": "Volume"
      }
     ]
    }
   ]
  },
  { "title": "VOO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "VOO",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max by(symbol) (security_Open{symbol=~\"\", collapse=\"$Collapse\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "max by(symbol) (security_Close{symbol=~\"\", collapse=\"$Collapse\"})",
     "legendFormat": "Close"
    },
    {
     "expr": "max by(symbol) (security_High{symbol=~\"\", collapse=\"$Collapse\"})",
     "legendFormat": "High"
    },
    {
     "expr": "max by(symbol) (security_Low{symbol=~\"\", collapse=\"$Collapse\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "max by(symbol) (security_Volume{symbol=~\"\", collapse=\"$Collapse\"})",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "VOO Individual Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "$SP500",
     "type": "candlestick",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 224 },
     "repeat": "SP500",
     "targets": [
      {
       "expr": "max by(symbol) (security_Open{symbol=~\"$SP500\", collapse=\"day\"})",
       "legendFormat": "Open"
      },
      {
       "expr": "max by(symbol) (security_Close{symbol=~\"$SP500\", collapse=\"$Collapse\"})",
       "legendFormat": "Close"
      },
      {
       "expr": "max by(symbol) (security_Low{symbol=~\"$SP500\", collapse=\"day\"})",
       "legendFormat": "Low"
      },
      {
       "expr": "max by(symbol) (security_High{symbol=~\"$SP500\", collapse=\"day\"})",
       "legendFormat": "High"
      },
      {
       "expr": "max by(symbol) (security_Volume{symbol=~\"$SP500\", collapse=\"day\"})",
       "legendFormat": "Volume"
      }
     ]
    }
   ]
  }
 ]
}