{
 "title": "NVIDIA",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_NVIDIA", "query": "prometheus" },
   {
    "name": "Device",
    "query": {
     "query": "label_values(nvidia_smi_memory_free, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "Device",
   "targets": [
    {
     "expr": "{__name__=~\"nvidia_smi_cuda_version|nvidia_smi_driver_version|nvidia_smi_pcie_link_gen_current|nvidia_smi_pcie_link_width_current\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "compute_mode" ], "type": "tag" },
      { "params": [ "pstate" ], "type": "tag" },
      { "params": [ "uuid" ], "type": "tag" },
      { "params": [ "index" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "driver_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "driver_version" ], "type": "alias" }
      ],
      [
       { "params": [ "cuda_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "cuda_version" ], "type": "alias" }
      ],
      [
       { "params": [ "pcie_link_gen_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "pcie_link_gen_current" ], "type": "alias" }
      ],
      [
       { "params": [ "pcie_link_width_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "pcie_link_width_current" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  { "title": "$Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "Device" },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_memory_free{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_memory_free"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_memory_total{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_memory_total"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_memory_used{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_memory_used"
    }
   ]
  },
  {
   "title": "Clock Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_clocks_current_graphics{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_clocks_current_graphics"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_clocks_current_memory{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_clocks_current_memory"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_clocks_current_sm{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_clocks_current_sm"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_clocks_current_video{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_clocks_current_video"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_utilization_decoder{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_utilization_decoder"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_utilization_encoder{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_utilization_encoder"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_utilization_gpu{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_utilization_gpu"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_utilization_memory{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_utilization_memory"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_power_draw{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_power_draw"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_fan_speed{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_fan_speed"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_temperature_gpu{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_temperature_gpu"
    }
   ]
  },
  {
   "title": "Encoder Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_encoder_stats_average_fps{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_encoder_stats_average_fps"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_encoder_stats_average_latency{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_encoder_stats_average_latency"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_encoder_stats_session_count{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_encoder_stats_session_count"
    }
   ]
  },
  {
   "title": "FBC Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_fbc_stats_average_fps{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_fbc_stats_average_fps"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_fbc_stats_average_latency{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_fbc_stats_average_latency"
    },
    {
     "expr": "max by(uuid) (nvidia_smi_fbc_stats_session_count{name=\"$Device\"})",
     "legendFormat": "nvidia_smi_fbc_stats_session_count"
    }
   ]
  }
 ]
}