{
 "title": "Stonk",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "Company",
    "query": {
     "query": "label_values(nasdaq_stock_Value, companyName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stock Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Intraday Stock Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "expr": "nasdaq_stock_Value{companyName=\"$Company\", collapse=\"minute\"}",
     "legendFormat": "__auto",
     "measurement": "nasdaq_stock",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$Company$/" },
      { "condition": "AND", "key": "collapse", "operator": "=", "value": "minute" }
     ]
    }
   ]
  },
  {
   "title": "Intraday Stock Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "expr": "nasdaq_stock_Volume{companyName=\"$Company\", collapse=\"minute\"}",
     "legendFormat": "__auto",
     "measurement": "nasdaq_stock",
     "select": [
      [
       { "params": [ "Volume" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$Company$/" },
      { "condition": "AND", "key": "collapse", "operator": "=", "value": "minute" }
     ]
    }
   ]
  },
  {
   "title": "Historical Stock Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$col ($tag_collapse)",
     "expr": "nasdaq_stock_Open{companyName=\"$Company\"}",
     "groupBy": [
      { "params": [ "collapse" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "nasdaq_stock",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" }
      ],
      [
       { "params": [ "Close" ], "type": "field" }
      ],
      [
       { "params": [ "High" ], "type": "field" }
      ],
      [
       { "params": [ "Low" ], "type": "field" }
      ],
      [
       { "params": [ "Open" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$Company$/" },
      { "condition": "AND", "key": "collapse", "operator": "!=", "value": "minute" }
     ]
    },
    {
     "expr": "nasdaq_stock_Close{companyName=\"$Company\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nasdaq_stock_Low{companyName=\"$Company\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nasdaq_stock_High{companyName=\"$Company\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical Stock Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "$col ($tag_collapse)",
     "expr": "nasdaq_stock_Volume{companyName=\"$Company\", collapse!=\"minute\"}",
     "groupBy": [
      { "params": [ "collapse" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "nasdaq_stock",
     "select": [
      [
       { "params": [ "Volume" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$Company$/" },
      { "condition": "AND", "key": "collapse", "operator": "!=", "value": "minute" }
     ]
    }
   ]
  }
 ]
}