#! /usr/bin/env sh
bspc monitor -d web code model social game idle other

bspc config border_width 0
bspc config window_gap 0

# Useless since space is reserved from Polybar
bspc config top_padding 20
bspc config bottom_padding 20
bspc config left_padding 20
bspc config right_padding 20

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc desktop ^1 -l monocle
bspc desktop ^2 -l monocle

bspc rule -a Vivaldi-stable -o desktop=^1
bspc rule -a Code -o desktop=^2
bspc rule -a Blender -o desktop=^3
bspc rule -a discord -o desktop=^4
bspc rule -a EVE -o desktop=^5

bspc rule -a Steam state=floating
bspc rule -a Zenity state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Pinentry state=floating
bspc rule -a Xfce4-screenshooter state=floating
bspc rule -a Xfce4-notifyd-config state=floating

bspc config click_to_focus any
bspc config focus_follows_pointer true
bspc config external_rules_command ~/.bspwm/external_rules

bspc config presel_feedback_color \#aaaaaa
