#! /usr/bin/env sh
wid=$1
class=$2
instance=$3

if [[ "$instance" == GLava ]]; then
  # Keep above xwinwrap (root window)
  # xdo above -t "$(xdo id -n root | sort | head -n 1)" $wid
  # Actually let's just put on top of everything
  xdo raise $wid
else
  # Lower everything else
  xdo below -t "$(xdo id -a GLava)" $wid
fi
