#! /usr/bin/env bash
spaces () {
  # Default to 10 workspaces
  N_WORKSPACES="${1-10}"
  WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')

  seq 1 "${N_WORKSPACES}" | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc \
    'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
    # 'map(tostring) | map({id: ., windows: ($windows[.]//0)}) | map(select(.windows > 0))'
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | \
  while read -r line;
  do
    spaces
  done
