{
  name = "enable-kvm-virtualisation";
  patch = null;
  extraConfig = ''
    ARM64_ERRATUM_834220=y

    HAVE_KVM_IRQCHIP=y
    HAVE_KVM_IRQFD=y
    HAVE_KVM_IRQ_ROUTING=y
    HAVE_KVM_EVENTFD=y
    KVM_MMIO=y
    HAVE_KVM_MSI=y
    HAVE_KVM_CPU_RELAX_INTERCEPT=y
    KVM_VFIO=y
    HAVE_KVM_ARCH_TLB_FLUSH_ALL=y
    KVM_GENERIC_DIRTYLOG_READ_PROTECT=y
    HAVE_KVM_IRQ_BYPASS=y
    HAVE_KVM_VCPU_RUN_PID_CHANGE=y
    IRQ_BYPASS_MANAGER=y
    VIRTUALIZATION=y
    KVM=y
    KVM_ARM_HOST=y
    KVM_ARM_PMU=y
    KVM_INDIRECT_VECTORS=y
    VHOST_NET=m
    VHOST_SCSI=m
    VHOST_VSOCK=m
    VHOST=m
    VHOST_CROSS_ENDIAN_LEGACY=y

    PREEMPT_NOTIFIERS=y
  '';
}
