name: "nixos-configuration"
on:
  push:
  pull_request:
jobs:
  isoImage:
    runs-on: ubuntu-latest
    steps:
    # WARNING: Needed due to GitHub Actions disk space regression on Linux runners
    - name: init
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v8
    - name: build
      run: |
        nix-shell -I nixpkgs=https://github.com/eadwu/nixpkgs/archive/develop.tar.gz -p nixFlakes --run \
          'nix --experimental-features "flakes nix-command" build --print-build-logs --recreate-lock-file "$(pwd)#isoImage"'
    - uses: actions/upload-artifact@v2-preview
      with:
        path: iso/**/*.iso
